version: '3.9'
services:
  postgres:
    container_name: walletService
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_DB: walletService
      POSTGRES_PASSWORD: strelets
      POSTGRES_USER: strelets
    ports:
      - "5432:5432"